### ISSUE TITLE
Mouseover on Techs 

### ISSUE THREAD

**Issue by m7mdcc** [smashah/smashah#1]
Hi , Nice Personal Page .. 

I suggest when user mouse over the techs icons , must show like tip that contain tech name
![image](https://user-images.githubusercontent.com/3501383/95322824-c7d23400-08a5-11eb-812a-d683871bd864.png)

Best luck for you

**Comment by smashah** [comment]
never realized people could make issues on a profile ha! Thanks, Mohammed, this is fixed now 👍🏼 Wish you all the best inshallah :)
